# Generated by Django 4.1.2 on 2022-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande_status_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total_trans',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
