# Generated by Django 4.1.2 on 2022-11-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_produit_options_produit_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
